# Generated by Django 2.1.5 on 2020-05-10 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='enter your email', max_length=254, null=True)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default='male', max_length=50)),
                ('age', models.CharField(default=18, max_length=20)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20)),
                ('time', models.CharField(choices=[('morning', 'morning'), ('day', 'day'), ('evening', 'evening')], default='moring', max_length=20, verbose_name='GYM Time')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Moring'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='Moring', max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.GymInfromation')),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('age', models.CharField(max_length=20)),
                ('trainer_type', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.CharField(max_length=20)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GYM.Trainers'),
        ),
    ]
