# Generated by Django 3.0.5 on 2020-05-01 04:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='enter your email', max_length=254, null=True)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default='male', max_length=50)),
                ('age', models.CharField(default=18, max_length=20)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20)),
                ('pan_number', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Member', 'member'), ('GYM Owner', 'GYM Owner')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
