# Generated by Django 2.1.5 on 2020-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.CharField(max_length=20),
        ),
    ]
