# Generated by Django 2.1.5 on 2020-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        ('GYM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.GymInfromation'),
        ),
    ]
