# Generated by Django 2.1 on 2020-05-02 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0002_trainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='enter your email', max_length=254, null=True)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default='male', max_length=50)),
                ('age', models.CharField(default=18, max_length=20)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20)),
                ('time', models.CharField(choices=[('morning', 'morning'), ('day', 'day'), ('evening', 'evening')], default='moring', max_length=20, verbose_name='GYM Time')),
            ],
        ),
    ]
