# Generated by Django 2.1.5 on 2020-05-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        ('GYM', '0002_trainers_gym'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='UserSchedule',
        ),
    ]
