# Generated by Django 2.1.5 on 2020-05-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_auto_20200513_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.UserInformation'),
        ),
    ]
