# Generated by Django 2.1 on 2020-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='pic',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
