# Generated by Django 2.1.5 on 2020-05-20 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_auto_20200520_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
