# Generated by Django 2.1.5 on 2020-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_auto_20200520_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
