# Generated by Django 2.1 on 2020-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_trainers_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='pic',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='images'),
        ),
    ]
