# Generated by Django 2.1.5 on 2020-05-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_auto_20200513_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.UserInformation'),
        ),
    ]
