# Generated by Django 2.1 on 2020-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0005_auto_20200504_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='pic',
            field=models.ImageField(blank=True, max_length=15, null=True, upload_to='images'),
        ),
    ]
