# Generated by Django 2.1.5 on 2020-05-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        ('GYM', '0005_gymcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcontent',
            name='gym',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.GymInfromation'),
            preserve_default=False,
        ),
    ]
