# Generated by Django 2.1 on 2020-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0006_auto_20200504_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
