# Generated by Django 2.1 on 2020-05-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0007_auto_20200505_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
