# Generated by Django 2.1.5 on 2020-05-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0009_auto_20200521_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
