# Generated by Django 2.1.5 on 2020-05-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0010_auto_20200521_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='gym',
        ),
    ]
