# Generated by Django 2.1 on 2020-05-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0011_auto_20200508_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endtime',
            field=models.CharField(max_length=20),
        ),
    ]
