# Generated by Django 2.1 on 2020-05-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0012_auto_20200508_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='starttime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
