# Generated by Django 2.1 on 2020-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0013_auto_20200508_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='endtime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='starttime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('morning', 'Moring'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='Moring', max_length=50),
        ),
    ]
